### ISSUE TITLE
How to show the feature maps

### ISSUE THREAD

**Issue by albert-666** [SCUT-AILab/DCP#13]
I like your feature maps shown in the paper very much. The color matching is so good. Do you draw the feature maps with imshow function in matplotlib? Which colormap do you choose? Or other methods to show the beautiful feature maps? I try to show feature maps but they look ugly. Are there any advice? Thanks  you very much!

**Comment by liujingcs** [comment]
We visualize the feature map through matplotlib using 'jet' colormap.
