### ISSUE TITLE
Algorithm 1 fine-tuning 

### ISSUE THREAD

**Issue by kakusikun** [SCUT-AILab/DCP#2]
In Algorithm 1, "Learn theta and Fine-tune M with (L^S)_p and L_f." which means that the weights of the first layer to layer L_p will be updated w.r.t to (L^S)_p and whole model weight will be updated w.r.t L_f (the final loss), is that right?

[In this line](https://github.com/SCUT-AILab/Discrimination-aware-Channel-Pruning-for-Deep-Neural-Networks/blob/master/dcp/trainer.py#L314), I can understand that `i != index` is going to update weights of the first layer to layer L_p by `self.seg_optimizer[i].step()` but the `i != len(self.pruned_segments) - 1` is going to update weights of the first layer to the end of the second-last segment. 

According to Algorithm 1, it should be the last segment, that is, the whole model, but why the second-last segment?

**Comment by liujingcs** [comment]
The `i != len(self.pruned_segments) - 1` indeed is going to update weights of the first layer to the end of the last segment.

**Comment by kakusikun** [comment]
That's right. I forgot the zero-based index. Thanks for correction.
