### ISSUE TITLE
Hello, I would like to ask where to find the pre trained model here: /home/liujing/NFS/TPAMI_channel_pruning/baseline/cifar10_resnet56/log_PreResNet56_cifar10_bs128_lr0.100_epoch400_baseline_110503_repeat/check_point/best_model.pth in cifar10_resnet.hocon

### ISSUE THREAD

**Issue by LLLiuxiaofang** [SCUT-AILab/DCP#21]

**Comment by liujingcs** [comment]
Please find the pre-trained model at https://github.com/SCUT-AILab/DCP/releases.

**Comment by LLLiuxiaofang** [comment]
> Please find the pre-trained model at https://github.com/SCUT-AILab/DCP/releases.

Thank you very much for answering me!! But the pre-trained model used in your auxnet folder is not the resnet56_pretrained.pth  you provided.  What I'm talking about is the position of the pre-trained model in resume or retrain options. Looking forward to your reply.

**Comment by liujingcs** [comment]
The resnet56_pretrained.pth is indeed the pretrained model for auxnet folder. The pretrained model for CIFAR-10 can be accessed at https://github.com/SCUT-AILab/DCP/releases/tag/0.1.2. The pretrained model for ImageNet is available on torchvision.
