### ISSUE TITLE
About "replace the baseline model"

### ISSUE THREAD

**Issue by kakusikun** [SCUT-AILab/DCP#4]
[Here](https://github.com/SCUT-AILab/Discrimination-aware-Channel-Pruning-for-Deep-Neural-Networks/blob/master/dcp/channel_pruning.py#L450) is going to copy modules of pruned_modules, why don't you just do 

`self.ori_model = copy.deepcopy(self.pruned_model)` 

,but copy modules by modules?
Is there any concern?

**Comment by liujingcs** [comment]
You are right. We can use `self.ori_model = copy.deepcopy(self.pruned_model)` to simplify our code.

**Comment by kakusikun** [comment]
Thanks for your reply. This method can be customized easier.
